services:
  postiz:
    build:
      context: .
      dockerfile: Dockerfile.dev
      target: dist
    container_name: postiz
    restart: always
    env_file: .env
    environment:
      # Database and Redis connection strings for Docker networking
      DATABASE_URL: "postgresql://${POSTGRES_USER:-postiz-user}:${POSTGRES_PASSWORD:-postiz-password}@postiz-postgres:5432/${POSTGRES_DB:-postiz-db-local}"
      REDIS_URL: "redis://postiz-redis:6379"
      # The container images are pre-configured to use /uploads for file storage
      UPLOAD_DIRECTORY: "/uploads"
      NEXT_PUBLIC_UPLOAD_DIRECTORY: "/uploads"
      IS_GENERAL: "true" # Required for self-hosting
    volumes:
      - postiz-config:/config/
      - postiz-uploads:/uploads/
    ports:
      - 3001:3000  # Backend API
      - 3002:3001  # Main URL
      - 4200:4200  # Frontend
      - 5000:5000  # Default port
    networks:
      - postiz-network
    depends_on:
      postiz-postgres:
        condition: service_healthy
      postiz-redis:
        condition: service_healthy
 
  postiz-postgres:
    image: postgres:17-alpine
    container_name: postiz-postgres
    restart: always
    env_file: .env
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postiz-password}
      POSTGRES_USER: ${POSTGRES_USER:-postiz-user}
      POSTGRES_DB: ${POSTGRES_DB:-postiz-db-local}
    volumes:
      - postgres-volume:/var/lib/postgresql/data
    networks:
      - postiz-network
    healthcheck:
      test: pg_isready -U ${POSTGRES_USER:-postiz-user} -d ${POSTGRES_DB:-postiz-db-local}
      interval: 10s
      timeout: 3s
      retries: 3
  postiz-redis:
    image: redis:7.2
    container_name: postiz-redis
    restart: always
    env_file: .env
    healthcheck:
      test: redis-cli ping
      interval: 10s
      timeout: 3s
      retries: 3
    volumes:
      - postiz-redis-data:/data
    networks:
      - postiz-network
 
 
volumes:
  postgres-volume:
    external: false
 
  postiz-redis-data:
    external: false
 
  postiz-config:
    external: false
 
  postiz-uploads:
    external: false
 
networks:
  postiz-network:
    external: false